import { FormSectionType } from "../../types/formTypes";
import { FaGlobe } from "react-icons/fa6";

import {
  AltinAyarData,
  AltinRengiData,
  AtolyeListesi,
  SadeModelTurleri,
} from "@/data/Sade.data";
import {
  PirlantaBerraklikData,
  PirlantaBoyKodlari,
  PirlantaElekData,
  PirlantaKesimKodlariData,
  PirlantaRenkData,
} from "@/data/Pirlanta.data";
import {
  RenkliTasListesiData,
  RenkliTasListesiKesimData,
  RenkliTasListesiMenseiList,
  RenkliTasRenkListesi,
} from "@/data/RenkliTas.data";
import { GenerateSertificateUrl } from "./Pirlanta.Utils";

export const AddSadeSections: Array<FormSectionType> = [
  {
    colsLenght: "12",
    sectionTitle: "Sade Bilgileri",
    groupNumber: 0,
    keyString: "properties",
    elements: [
      {
        name: "type",
        type: "customButtonGroup",
        title: "Tip",
        checkBoxList: ["Stok", "Sipariş"],
        required: true,
        requiredMessage: "Karat Değeri Boş Bırakılamaz",
        checkBoxSetValueItem: "type",
        isCodeRelated: true,
        span: 12,
      },
      {
        name: "resim",
        type: "file",
        title: "Ürün Görseli",
        placeholder: "Sade Ürün Görseli Seçiniz...",
        required: true,
        requiredMessage: "Sade Ürün Görseli Seçiniz",
        relativeTo: "type",
        span: 3,
        rowSpan: 5,
        showPicture: true,
        pictureExtraText: "PNG,JPG (MAX 3MB)",
      },

      {
        name: "sadeKodu",
        type: "text",
        title: "Sade Kodu",
        disabled: true,
        placeholder: "Sade Kodu Değerini Giriniz...",
        required: true,
        requiredMessage: "Sade Kodu Değeri Boş Bırakılamaz",
        span: 3,
      },
      {
        name: "modelTuru",
        type: "select",
        title: "Model Türü",
        placeholder: "Model Türü Değerini Giriniz...",
        required: true,
        requiredMessage: "Model Türü Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
        options: SadeModelTurleri,
      },
      {
        name: "modelKodu",
        type: "text",
        title: "Model Kodunu Giriniz",
        placeholder: "Model Kodu Değerini Giriniz...",
        required: true,
        requiredMessage: "Model Kodu Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
        extraValidations: {
          maxLength: {
            value: 4,
            message: "Model Kodu 4 Haneden Oluşmalıdır ",
          },
          minLength: {
            value: 4,
            message: "Model Kodu 4 Haneden Oluşmalıdır",
          },
        },
      },
      {
        name: "atolye",
        type: "select",
        title: "Atölye Seçiniz",
        placeholder: "Atölye Değerini Giriniz...",
        required: true,
        requiredMessage: "Atölye Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
        options: AtolyeListesi,
      },
      {
        name: "iscilik",
        type: "number",
        title: "İşçilik",
        placeholder: "İşçilik Değerini Giriniz...",
        required: true,
        requiredMessage: "İşçilik Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 2,
      },
      {
        name: "cost_currency",
        type: "select",
        title: "Birim",
        placeholder: "Birim Değerini Giriniz...",
        required: true,
        requiredMessage: "Birim Değeri Boş Bırakılamaz",
        relativeTo: "type",
        options: [
          { titleVal: "HAS", valueVal: "HAS" },
          { titleVal: "USD", valueVal: "USD" },
        ],
        span: 1,
      },
      {
        name: "altinRengi",
        type: "select",
        title: "Altın Rengi",
        placeholder: "Altın Rengi Değerini Giriniz...",
        required: true,
        requiredMessage: "Altın Rengi Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
        options: AltinRengiData,
      },
      {
        name: "gram",
        type: "number",
        title: "Gram",
        placeholder: "Gram Değerini Giriniz...",
        required: true,
        requiredMessage: "Gram Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
      },
      {
        name: "ayar",
        type: "select",
        title: "Ayar",
        placeholder: "Ayar Değerini Giriniz...",
        required: true,
        requiredMessage: "Ayar Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
        options: AltinAyarData,
      },
      {
        name: "hasGrami",
        type: "text",
        title: "Has Gramı",
        placeholder: "Has Gramı Değerini Giriniz...",
        required: true,
        requiredMessage: "Has Gramı Değeri Boş Bırakılamaz",
        disabled: true,
        span: 3,
      },
      {
        name: "aciklama",
        type: "text",
        title: "Açıklama",
        placeholder: "Açıklama Değerini Giriniz...",
        required: false,
        requiredMessage: "Açıklama Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
        rowSpan: 2,
        colStart: "4",
        colEnd: "10",
      },
      {
        name: "girisTarihi",
        type: "datepicker",
        title: "Giriş Tarihi",
        placeholder: "Giriş Tarihi Değerini Giriniz...",
        required: true,
        requiredMessage: "Giriş Tarihi Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
      },
    ],
  },
];

export const AddStoneSections: Array<FormSectionType> = [
  {
    colsLenght: "8",
    sectionTitle: "Pırlanta Bilgileri",
    groupNumber: 0,
    keyString: "properties",
    extraElementRelativeTo: "menstrual_status",
    extraElementVisibleRelative: "Sertifikalı",
    extraElements: [
      {
        name: "fromsingleormixed",
        type: "customButtonGroup",
        title: "Tip",
        checkBoxList: ["From Single", "From Mixed"],
        required: true,
        requiredMessage: "Karat Değeri Boş Bırakılamaz",
        checkBoxSetValueItem: "fromsingleormixed",
        span: 4,
        value: "From Single",
        isCodeRelated: true,
      },
      {
        name: "frommixedItem",
        type: "select",
        title: "Mixed Grubu",
        required: true,
        requiredMessage: "Kesim Değerini Boş Bırakılamaz",
        relativeTo: "fromsingleormixed",
        visibleRelative: "From Mixed",
        isExtra: true,
        isCodeRelated: true,
        span: 4,
      },
    ],
    elements: [
      {
        name: "menstrual_status",
        type: "customButtonGroup",
        checkBoxList: ["Sertifikalı", "Sertifikasız"],
        required: true,
        requiredMessage: "Karat Değeri Boş Bırakılamaz",
        checkBoxSetValueItem: "menstrual_status",
        span: 8,
        isCodeRelated: true,
      },
      {
        name: "kesim",
        type: "select",
        title: "Kesim",
        placeholder: "Kesim Değerini Giriniz...",
        required: true,
        requiredMessage: "Kesim Değerini Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        isCodeRelated: true,
        options: PirlantaKesimKodlariData,
        span: 2,
      },
      {
        name: "carat",
        type: "number",
        title: "Karat",
        placeholder: "Karat Değerini Giriniz...",
        required: true,
        requiredMessage: "Karat Değeri Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        span: 2,
        simgeturu: "caratType",
        showIconRelativeTo: "Sertifikalı",
      },
      {
        name: "renk",
        type: "select",
        title: "Renk",
        placeholder: "Renk Değerini Giriniz...",
        required: true,
        requiredMessage: "Renk Değeri Boş Bırakılamaz",
        options: PirlantaRenkData,
        relativeTo: "menstrual_status",
        span: 2,
        spesificRelatedItem: "Sertifikasız",
      },
      {
        name: "renk2",
        type: "select",
        title: "",
        placeholder: "Renk Değerini Giriniz...",
        required: true,
        requiredMessage: "Renk Değeri Boş Bırakılamaz",
        span: 1,
        options: PirlantaRenkData,
        relativeTo: "menstrual_status",
        visibleRelative: "Sertifikasız",
        isTopMargin: true,
      },
      {
        name: "berraklik",
        type: "select",
        title: "Berraklık",
        placeholder: "Berraklık Değerini Giriniz...",
        requiredMessage: "Berraklık Değeri Boş Bırakılamaz",
        required: true,
        relativeTo: "menstrual_status",
        span: 2,
        options: PirlantaBerraklikData,
        spesificRelatedItem: "Sertifikasız",
      },
      {
        name: "berraklik2",
        type: "select",
        title: "",
        placeholder: "Berraklık Değerini Giriniz...",
        requiredMessage: "Berraklık Değeri Boş Bırakılamaz",
        required: true,
        relativeTo: "menstrual_status",
        span: 1,
        options: PirlantaBerraklikData,
        visibleRelative: "Sertifikasız",
        isTopMargin: true,
      },
      {
        name: "mensei",
        type: "select",
        title: "Menşei",
        span: 2,

        placeholder: "Menşei Değerini Seçiniz...",
        required: true,
        requiredMessage: "Menşei Değeri Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        // showIconRelativeTo: "Sertifikasız",
        staticOptions: RenkliTasListesiMenseiList,
      },

      {
        name: "elek",
        type: "select",
        title: "Elek",
        placeholder: "Elek Değerini Giriniz...",
        required: false,
        requiredMessage: "Elek Değeri Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        visibleRelative: "Sertifikasız",
        span: 2,
        options: PirlantaElekData,
      },

      {
        name: "boy",
        type: "select",
        title: "Boy",
        span: 2,
        isCodeRelated: true,
        placeholder: "Boy Değerini Giriniz...",
        required: true,
        requiredMessage: "Boy Değeri Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        showIconRelativeTo: "Sertifikasız",
        options: PirlantaBoyKodlari,
      },

      {
        name: "aciklama",
        type: "text",
        title: "Açıklama",
        placeholder: "Açıklama Değerini Giriniz...",
        relativeTo: "menstrual_status",
        required: false,
        requiredMessage: "Açıklama Değeri Boş Bırakılamaz",
        span: 4,
      },
    ],
  },
  {
    visibleRelativeColumn: "menstrual_status",
    colsLenght: "12",
    visibleRelativeToValue: "Sertifikalı",
    sectionTitle: "Sertifika Bilgileri",
    groupNumber: 1,
    keyString: "product_certificate",
    elements: [
      {
        name: "sertifika",
        type: "select",
        title: "Sertifika",
        placeholder: "Sertifika Seçiniz...",
        required: false,
        span: 3,
        requiredMessage: "Kesim Değerini Boş Bırakılamaz",
        options: [
          {
            titleVal: "HRD",
            valueVal: "HRD",
          },
          {
            titleVal: "GIA",
            valueVal: "GIA",
          },
          {
            titleVal: "NONE",
            valueVal: "NONE",
          },
        ],
      },

      {
        name: "sertifikaNo",
        type: "text",
        relativeTo: "sertifika",
        title: "Sertifika No",
        placeholder: "Sertifika No Değerini Giriniz...",
        required: true,
        requiredMessage: "Sertifika No Değeri Boş Bırakılamaz",
        disabled: true,
        span: 3,
        isLinkedWithIcon: true,
        rightIcon: <FaGlobe />,
        extraFunction: GenerateSertificateUrl,
      },
      {
        name: "sertifikaTarihi",
        type: "datepicker",
        title: "Sertifika Tarihi",
        placeholder: "Sertifika Tarihi Değerini Giriniz...",
        required: true,
        requiredMessage: "Sertifika Tarihi Değeri Boş Bırakılamaz",
        disabled: true,
        relativeTo: "sertifika",
        span: 3,
      },
      {
        name: "sertifikaDosyasi",
        type: "file",
        relativeTo: "sertifika",
        title: "Sertifika Dosyası",
        placeholder: "Sertifika Dosyası Seçiniz...",
        required: false,
        requiredMessage: "Sertifika No Değeri Boş Bırakılamaz",
        disabled: true,
        span: 3,
      },
      {
        name: "propotion",
        type: "select",
        title: "Propotion",
        placeholder: "Propotion Seçiniz...",
        required: true,
        disabled: true,
        span: 3,
        relativeTo: "sertifika",
        requiredMessage: "Propotion Değerini Boş Bırakılamaz",
        options: [
          {
            titleVal: "EXC",
            valueVal: "EXC",
          },
          {
            titleVal: "VG",
            valueVal: "VG",
          },
          {
            titleVal: "F",
            valueVal: "F",
          },
          {
            titleVal: "P",
            valueVal: "P",
          },
          {
            titleVal: "-",
            valueVal: "-",
          },
        ],
      },
      {
        name: "polish",
        type: "select",
        title: "Polish",
        relativeTo: "sertifika",
        placeholder: "Polish Seçiniz...",
        required: true,
        disabled: true,
        requiredMessage: "Polish Değerini Boş Bırakılamaz",
        span: 3,
        options: [
          {
            titleVal: "EXC",
            valueVal: "EXC",
          },
          {
            titleVal: "VG",
            valueVal: "VG",
          },
          {
            titleVal: "F",
            valueVal: "F",
          },
          {
            titleVal: "P",
            valueVal: "P",
          },
        ],
      },
      {
        name: "symmetry",
        type: "select",
        title: "Symmetry",
        placeholder: "Symmetry Seçiniz...",
        required: true,
        disabled: true,
        relativeTo: "sertifika",
        span: 3,
        requiredMessage: "Symmetry Değerini Boş Bırakılamaz",
        options: [
          {
            titleVal: "EXC",
            valueVal: "EXC",
          },
          {
            titleVal: "VG",
            valueVal: "VG",
          },
          {
            titleVal: "F",
            valueVal: "F",
          },
          {
            titleVal: "P",
            valueVal: "P",
          },
        ],
      },
      {
        name: "fluorescence",
        type: "select",
        title: "Fluorescence",
        placeholder: "Fluorescence Seçiniz...",
        required: true,
        relativeTo: "sertifika",
        span: 3,
        disabled: true,
        requiredMessage: "Fluorescence Değerini Boş Bırakılamaz",
        options: [
          {
            titleVal: "NONE",
            valueVal: "NONE",
          },
          {
            titleVal: "FAINT",
            valueVal: "FAINT",
          },
          {
            titleVal: "MEDIUM",
            valueVal: "MEDIUM",
          },
          {
            titleVal: "STRONG",
            valueVal: "STRONG",
          },
          {
            titleVal: "SLIGHT",
            valueVal: "SLIGHT",
          },
        ],
      },
      {
        name: "min",
        type: "number",
        title: "Min",
        placeholder: "Min  Değerini Giriniz...",
        required: true,
        relativeTo: "sertifika",
        requiredMessage: "Min Değeri Boş Bırakılamaz",
        disabled: true,
        span: 4,
      },
      {
        name: "max",
        type: "number",
        title: "Max",
        placeholder: "Max Değerini Giriniz...",
        required: true,
        requiredMessage: "Max Değeri Boş Bırakılamaz",
        disabled: true,
        relativeTo: "sertifika",
        span: 4,
      },
      {
        name: "height",
        type: "number",
        title: "Height",
        placeholder: "Height Değerini Giriniz...",
        required: true,
        relativeTo: "sertifika",
        requiredMessage: "Height Değeri Boş Bırakılamaz",
        disabled: true,
        span: 4,
      },
      {
        name: "table",
        type: "number",
        title: "Table",
        placeholder: "Table Değerini Giriniz...",
        required: true,
        requiredMessage: "Table Değeri Boş Bırakılamaz",
        disabled: true,
        relativeTo: "sertifika",
        span: 4,
        rightIcon: "%",
      },
      {
        name: "totalDepth",
        type: "number",
        title: "Total Depth",
        placeholder: "Total Depth Değerini Giriniz...",
        required: true,
        requiredMessage: "Total Depth Değeri Boş Bırakılamaz",
        disabled: true,
        relativeTo: "sertifika",
        span: 4,
        rightIcon: "%",
      },
      {
        name: "girdle",
        type: "number",
        title: "Girdle",
        placeholder: "Girdle Değerini Giriniz...",
        required: true,
        relativeTo: "sertifika",
        requiredMessage: "Girdle Değeri Boş Bırakılamaz",
        disabled: true,
        span: 4,
      },
    ],
  },
  {
    colsLenght: "4",
    sectionTitle: "Pırlanta Fiyat Bilgileri",
    groupNumber: 1,
    keyString: "product_cost",
    elements: [
      {
        name: "buy_date",
        type: "datepicker",
        title: "Satin Alma Tarihi",
        placeholder: "Satın Alma Tarihi Değerini Giriniz...",
        required: true,
        requiredMessage: "Satın Alma Tarihi Değerini Boş Bırakılamaz",
        span: 1,
      },
      {
        name: "rapaportPrice",
        type: "text",
        title: "Rapaport Güncel Fiyatı",
        placeholder: "Rapaport Güncel Fiyatı...",
        required: true,
        requiredMessage: "Karat Değeri Boş Bırakılamaz",
        disabled: true,
        rightIcon: "$",
        value: "2500",
        isCurrency: true,
        span: 1,
        // relativeTo: "menstrual_status",
        // visibleRelative: "Sertifikalı",
      },
      {
        name: "iskonto",
        type: "number",
        title: "İskonto",
        placeholder: "İskonto...",
        required: true,
        requiredMessage: "İskonto Boş Bırakılamaz",
        span: 1,
        rightIcon: "$",
        // relativeTo: "menstrual_status",
        // visibleRelative: "Sertifikalı",
      },
      {
        name: "pricePerCarat",
        type: "text",
        title: "Price Per Carat",
        placeholder: "Price Per Carat...",
        required: false,
        requiredMessage: "İskonto Boş Bırakılamaz",
        disabled: true,
        isCurrency: true,
        rightIcon: "$",
        span: 1,
      },
      {
        name: "total_cost",
        type: "text",
        title: "Toplam Fiyat",
        placeholder: "Toplam Fiyat...",
        required: false,
        requiredMessage: "Toplam Fiyat Bırakılamaz",
        disabled: true,
        isCurrency: true,
        rightIcon: "$",
        colStart: "4",
        colEnd: "5",
        span: 1,
      },
    ],
  },
];

export const AddRenkliTasSections: Array<FormSectionType> = [
  {
    colsLenght: "8",
    sectionTitle: "Renkli Taş Bilgileri",
    groupNumber: 0,
    keyString: "properties",
    extraElementRelativeTo: "menstrual_status",
    extraElementVisibleRelative: "Sertifikalı",
    extraElements: [
      {
        name: "fromsingleormixed",
        type: "customButtonGroup",
        isCodeRelated: true,
        title: "Tip",
        checkBoxList: ["From Single", "From Mixed"],
        required: true,
        requiredMessage: "Karat Değeri Boş Bırakılamaz",
        checkBoxSetValueItem: "fromsingleormixed",
        span: 4,
        value: "From Single",
      },
      {
        name: "frommixedItem",
        type: "select",
        title: "Mixed Grubu",
        isCodeRelated: true,
        required: true,
        requiredMessage: "Kesim Değerini Boş Bırakılamaz",
        relativeTo: "fromsingleormixed",
        visibleRelative: "From Mixed",
        isExtra: true,
        span: 4,
      },
    ],
    elements: [
      {
        name: "menstrual_status",
        isCodeRelated: true,
        type: "customButtonGroup",
        checkBoxList: ["Sertifikalı", "Sertifikasız"],
        required: true,
        requiredMessage: "Karat Değeri Boş Bırakılamaz",
        checkBoxSetValueItem: "menstrual_status",
        span: 8,
      },
      {
        name: "renkliTas",
        type: "select",
        isCodeRelated: true,
        title: "Renkli Taş",
        placeholder: "Renkli Taş Seçiniz...",
        required: true,
        requiredMessage: "Renkli Taş Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        span: 2,
        options: RenkliTasListesiData,
      },
      {
        name: "carat",
        type: "number",
        title: "Karat",
        placeholder: "Karat Değerini Giriniz...",
        required: true,
        requiredMessage: "Karat Değeri Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        span: 2,
        // simgeturu: "caratType",
      },
      {
        name: "renk",
        type: "select",
        title: "Renk",
        placeholder: "Renk Seçiniz...",
        required: true,
        requiredMessage: "Renk Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        span: 2,
        options: RenkliTasRenkListesi,
      },
      {
        name: "kesim",
        type: "select",
        title: "Kesim",
        placeholder: "Kesim Değerini Giriniz...",
        required: true,
        requiredMessage: "Kesim Değerini Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        span: 2,
        options: RenkliTasListesiKesimData,
      },
      {
        name: "mensei",
        type: "select",
        title: "Menşei",
        placeholder: "Menşei Seçiniz...",
        required: false,
        requiredMessage: "Menşei Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        span: 2,
        staticOptions: RenkliTasListesiMenseiList,
      },
      {
        name: "treatment",
        type: "select",
        title: "Treatment",
        placeholder: "Treatment Seçiniz...",
        required: false,
        requiredMessage: "Treatment Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        span: 2,
        options: [
          {
            titleVal: "HEATED",
            valueVal: "HEATED",
          },
          {
            titleVal: "NOT HEATED",
            valueVal: "NOT HEATED",
          },
        ],
      },
      {
        name: "pricePerCarat",
        type: "text",
        title: "Price Per Carat",
        placeholder: "Price Per Carat...",
        required: true,
        requiredMessage: "Karat Başına Maliyet Giriniz",
        isCurrency: true,
        rightIcon: "$",
        disabled: true,
        span: 2,
      },
      {
        name: "total_cost",
        type: "number",
        title: "Toplam Fiyat",
        placeholder: "Toplam Fiyat...",
        required: true,
        requiredMessage: "Toplam Fiyat Boş Bırakılamaz",
        disabled: false,
        rightIcon: "$",
        span: 2,
      },
      // {
      //   name: "sertifikaDosyasi",
      //   type: "file",
      //   title: "Sertifika Dosyası",
      //   placeholder: "Sertifika Dosyası Seçiniz...",
      //   required: false,
      //   requiredMessage: "Sertifika Dosyası  Boş Bırakılamaz",
      //   disabled: true,
      //   span: 2,
      //   relativeTo: "menstrual_status",
      //   visibleRelative: "Sertifikalı",
      // },
    ],
  },
  {
    visibleRelativeColumn: "menstrual_status",
    colsLenght: "12",
    visibleRelativeToValue: "Sertifikalı",
    sectionTitle: "Sertifika Bilgileri",
    groupNumber: 1,
    keyString: "product_certificate",
    elements: [
      {
        name: "sertifika",
        type: "select",
        title: "Sertifika",
        placeholder: "Sertifika Seçiniz...",
        required: false,
        span: 3,
        requiredMessage: "Sertifika Değeri Boş Bırakılamaz",
        options: [
          {
            titleVal: "HRD",
            valueVal: "HRD",
          },
          {
            titleVal: "GIA",
            valueVal: "GIA",
          },
          {
            titleVal: "NONE",
            valueVal: "NONE",
          },
        ],
      },
      {
        name: "sertifikaNo",
        type: "text",
        relativeTo: "sertifika",
        title: "Sertifika No",
        placeholder: "Sertifika No Değerini Giriniz...",
        required: true,
        requiredMessage: "Sertifika No Değeri Boş Bırakılamaz",
        disabled: false,
        span: 3,
        isLinkedWithIcon: true,
        rightIcon: <FaGlobe />,
        extraFunction: GenerateSertificateUrl,
      },
      {
        name: "sertifikaTarihi",
        type: "datepicker",
        title: "Sertifika Tarihi",
        placeholder: "Sertifika Tarihi Değerini Giriniz...",
        required: true,
        requiredMessage: "Sertifika Tarihi Değeri Boş Bırakılamaz",
        disabled: false,
        relativeTo: "sertifika",
        span: 3,
      },

      {
        name: "sertifikaDosyasi",
        type: "file",
        relativeTo: "sertifika",
        title: "Sertifika Dosyası",
        placeholder: "Sertifika Dosyası Seçiniz...",
        required: false,
        requiredMessage: "Sertifika No Değeri Boş Bırakılamaz",
        disabled: true,
        span: 3,
      },
    ],
  },
];
