import { FormSectionType } from "../../types/formTypes";
import { CustomOptionType } from "../../types/inputTypes";
import {
  AtolyeListesi,
  PirlantaBoyKodlari,
  RenkliTasListesiData,
  RenkliTasRenkListesi,
  SadeModelTurleriData,
} from ".";
import { MenseiList } from "./Mensei";

export const AddSadeSections: Array<FormSectionType> = [
  {
    colsLenght: "12",
    sectionTitle: "Sade Bilgileri",
    groupNumber: 0,
    keyString: "properties",
    elements: [
      {
        name: "type",
        type: "customButtonGroup",
        title: "Tip",
        checkBoxList: ["Stok", "Sipariş"],
        required: true,
        requiredMessage: "Karat Değeri Boş Bırakılamaz",
        checkBoxSetValueItem: "type",
        isCodeRelated: true,
        span: 12,
      },
      {
        name: "resim",
        type: "file",
        title: "Ürün Görseli",
        placeholder: "Sade Ürün Görseli Seçiniz...",
        required: true,
        requiredMessage: "Sade Ürün Görseli Seçiniz",
        relativeTo: "type",
        span: 3,
        rowSpan: 5,
        showPicture: true,
        pictureExtraText: "PNG,JPG (MAX 3MB)",
      },

      {
        name: "sadeKodu",
        type: "text",
        title: "Sade Kodu",
        disabled: true,
        placeholder: "Sade Kodu Değerini Giriniz...",
        required: true,
        requiredMessage: "Sade Kodu Değeri Boş Bırakılamaz",
        span: 3,
      },
      {
        name: "modelTuru",
        type: "select",
        title: "Model Türü",
        placeholder: "Model Türü Değerini Giriniz...",
        required: true,
        requiredMessage: "Model Türü Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
        options: SadeModelTurleriData,
      },
      {
        name: "modelKodu",
        type: "text",
        title: "Model Kodunu Giriniz",
        placeholder: "Model Kodu Değerini Giriniz...",
        required: true,
        requiredMessage: "Model Kodu Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
        extraValidations: {
          maxLength: {
            value: 4,
            message: "Model Kodu 4 Haneden Oluşmalıdır ",
          },
          minLength: {
            value: 4,
            message: "Model Kodu 4 Haneden Oluşmalıdır",
          },
        },
      },
      {
        name: "atolye",
        type: "select",
        title: "Atölye Seçiniz",
        placeholder: "Atölye Değerini Giriniz...",
        required: true,
        requiredMessage: "Atölye Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
        options: AtolyeListesi,
      },
      {
        name: "iscilik",
        type: "number",
        title: "İşçilik",
        placeholder: "İşçilik Değerini Giriniz...",
        required: true,
        requiredMessage: "İşçilik Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 2,
      },
      {
        name: "cost_currency",
        type: "select",
        title: "Birim",
        placeholder: "Birim Değerini Giriniz...",
        required: true,
        requiredMessage: "Birim Değeri Boş Bırakılamaz",
        relativeTo: "type",
        options: [
          { titleVal: "HAS", valueVal: "HAS" },
          { titleVal: "USD", valueVal: "USD" },
        ],
        span: 1,
      },
      {
        name: "altinRengi",
        type: "select",
        title: "Altın Rengi",
        placeholder: "Altın Rengi Değerini Giriniz...",
        required: true,
        requiredMessage: "Altın Rengi Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
        options: [
          {
            titleVal: "Beyaz",
            valueVal: "Beyaz",
            extraValue: "W",
          },
          {
            titleVal: "Yeşil",
            valueVal: "Yeşil",
            extraValue: "G",
          },
          {
            titleVal: "Rose",
            valueVal: "Rose",
            extraValue: "R",
          },
          {
            titleVal: "Yeşil Beyaz",
            valueVal: "Yeşil Beyaz",
            extraValue: "GW",
          },
          {
            titleVal: "Beyaz Rose",
            valueVal: "Beyaz Rose",
            extraValue: "WR",
          },
          {
            titleVal: "Yeşil Rose",
            valueVal: "Yeşil Rose",
            extraValue: "GR",
          },
          {
            titleVal: "Çok Renkli",
            valueVal: "Çok Renkli",
            extraValue: "WGR",
          },
        ],
      },
      {
        name: "gram",
        type: "number",
        title: "Gram",
        placeholder: "Gram Değerini Giriniz...",
        required: true,
        requiredMessage: "Gram Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
      },
      {
        name: "ayar",
        type: "select",
        title: "Ayar",
        placeholder: "Ayar Değerini Giriniz...",
        required: true,
        requiredMessage: "Ayar Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
        options: [
          { titleVal: "18", valueVal: "18" },
          { titleVal: "14", valueVal: "14" },
          { titleVal: "8", valueVal: "8" },
          { titleVal: "750", valueVal: "750" },
          { titleVal: "585", valueVal: "585" },
          { titleVal: "22", valueVal: "22" },
          { titleVal: "24", valueVal: "24" },
        ],
      },
      {
        name: "hasGrami",
        type: "text",
        title: "Has Gramı",
        placeholder: "Has Gramı Değerini Giriniz...",
        required: true,
        requiredMessage: "Has Gramı Değeri Boş Bırakılamaz",
        disabled: true,
        span: 3,
      },
      {
        name: "aciklama",
        type: "text",
        title: "Açıklama",
        placeholder: "Açıklama Değerini Giriniz...",
        required: false,
        requiredMessage: "Açıklama Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
        rowSpan: 2,
        colStart: "4",
        colEnd: "10",
      },
      {
        name: "girisTarihi",
        type: "datepicker",
        title: "Giriş Tarihi",
        placeholder: "Giriş Tarihi Değerini Giriniz...",
        required: true,
        requiredMessage: "Giriş Tarihi Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
      },
    ],
  },
];

export const AddStoneSections: Array<FormSectionType> = [
  {
    colsLenght: "8",
    sectionTitle: "Pırlanta Bilgileri",
    groupNumber: 0,
    keyString: "properties",
    extraElementRelativeTo: "menstrual_status",
    extraElementVisibleRelative: "Sertifikalı",
    extraElements: [
      {
        name: "fromsingleormixed",
        type: "customButtonGroup",
        title: "Tip",
        checkBoxList: ["From Single", "From Mixed"],
        required: true,
        requiredMessage: "Karat Değeri Boş Bırakılamaz",
        checkBoxSetValueItem: "fromsingleormixed",
        span: 4,
        value: "From Single",
        isCodeRelated: true,
      },
      {
        name: "frommixedItem",
        type: "select",
        title: "Mixed Grubu",
        required: true,
        requiredMessage: "Kesim Değerini Boş Bırakılamaz",
        relativeTo: "fromsingleormixed",
        visibleRelative: "From Mixed",
        isExtra: true,
        isCodeRelated: true,
        span: 4,
      },
    ],
    elements: [
      {
        name: "menstrual_status",
        type: "customButtonGroup",
        checkBoxList: ["Sertifikalı", "Sertifikasız"],
        required: true,
        requiredMessage: "Karat Değeri Boş Bırakılamaz",
        checkBoxSetValueItem: "menstrual_status",
        span: 8,
        isCodeRelated: true,
      },
      {
        name: "kesim",
        type: "select",
        title: "Kesim",
        placeholder: "Kesim Değerini Giriniz...",
        required: true,
        requiredMessage: "Kesim Değerini Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        isCodeRelated: true,
        options: [
          {
            titleVal: "ROUND",
            valueVal: "ROUND",
            extraValue: "BR",
          },
          {
            titleVal: "HEART",
            valueVal: "HEART",
            extraValue: "HS",
          },
          {
            titleVal: "PEAR",
            valueVal: "PEAR",
            extraValue: "PS",
          },
          {
            titleVal: "MARQUISE",
            valueVal: "MARQUISE",
            extraValue: "MQ",
          },
          {
            titleVal: "OVAL",
            valueVal: "OVAL",
            extraValue: "OV",
          },
          {
            titleVal: "BAGET",
            valueVal: "BAGET",
            extraValue: "BG",
          },
          {
            titleVal: "TRAPEZ",
            valueVal: "TRAPEZ",
            extraValue: "TP",
          },
          {
            titleVal: "TRIANGLE",
            valueVal: "TRIANGLE",
            extraValue: "TR",
          },
          {
            titleVal: "PRENSES",
            valueVal: "PRENSES",
            extraValue: "PR",
          },
          {
            titleVal: "RADIANT",
            valueVal: "RADIANT",
            extraValue: "RD",
          },
          {
            titleVal: "EMERALD",
            valueVal: "EMERALD",
            extraValue: "EM",
          },
          {
            titleVal: "CUSHION",
            valueVal: "CUSHION",
            extraValue: "CS",
          },
        ],
        span: 2,
      },
      {
        name: "carat",
        type: "number",
        title: "Karat",
        placeholder: "Karat Değerini Giriniz...",
        required: true,
        requiredMessage: "Karat Değeri Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        span: 2,
        simgeturu: "caratType",
        showIconRelativeTo: "Sertifikalı",
      },
      {
        name: "renk",
        type: "select",
        title: "Renk",
        placeholder: "Renk Değerini Giriniz...",
        required: true,
        requiredMessage: "Renk Değeri Boş Bırakılamaz",
        options: [
          {
            titleVal: "D",
            valueVal: "D",
          },
          {
            titleVal: "E",
            valueVal: "E",
          },
          {
            titleVal: "F",
            valueVal: "F",
          },
          {
            titleVal: "G",
            valueVal: "G",
          },
          {
            titleVal: "H",
            valueVal: "H",
          },
          {
            titleVal: "I",
            valueVal: "I",
          },
          {
            titleVal: "J",
            valueVal: "J",
          },
          {
            titleVal: "K",
            valueVal: "K",
          },
          {
            titleVal: "L",
            valueVal: "L",
          },
          {
            titleVal: "M",
            valueVal: "M",
          },
          {
            titleVal: "N",
            valueVal: "N",
          },
          {
            titleVal: "O",
            valueVal: "O",
          },
          {
            titleVal: "P",
            valueVal: "P",
          },
          {
            titleVal: "Q",
            valueVal: "Q",
          },
          {
            titleVal: "R",
            valueVal: "R",
          },
          {
            titleVal: "S",
            valueVal: "S",
          },
          {
            titleVal: "T",
            valueVal: "T",
          },
          {
            titleVal: "U",
            valueVal: "U",
          },
          {
            titleVal: "V",
            valueVal: "V",
          },
          {
            titleVal: "W",
            valueVal: "W",
          },
          {
            titleVal: "X",
            valueVal: "X",
          },
          {
            titleVal: "Y",
            valueVal: "Y",
          },
          {
            titleVal: "Z",
            valueVal: "Z",
          },
          {
            titleVal: "BLACK",
            valueVal: "BLACK",
          },
        ],
        relativeTo: "menstrual_status",
        span: 2,
        spesificRelatedItem: "Sertifikasız",
      },
      {
        name: "renk2",
        type: "select",
        title: "",
        placeholder: "Renk Değerini Giriniz...",
        required: true,
        requiredMessage: "Renk Değeri Boş Bırakılamaz",
        span: 1,
        options: [
          {
            titleVal: "D",
            valueVal: "D",
          },
          {
            titleVal: "E",
            valueVal: "E",
          },
          {
            titleVal: "F",
            valueVal: "F",
          },
          {
            titleVal: "G",
            valueVal: "G",
          },
          {
            titleVal: "H",
            valueVal: "H",
          },
          {
            titleVal: "I",
            valueVal: "I",
          },
          {
            titleVal: "J",
            valueVal: "J",
          },
          {
            titleVal: "K",
            valueVal: "K",
          },
          {
            titleVal: "L",
            valueVal: "L",
          },
          {
            titleVal: "M",
            valueVal: "M",
          },
          {
            titleVal: "N",
            valueVal: "N",
          },
          {
            titleVal: "O",
            valueVal: "O",
          },
          {
            titleVal: "P",
            valueVal: "P",
          },
          {
            titleVal: "Q",
            valueVal: "Q",
          },
          {
            titleVal: "R",
            valueVal: "R",
          },
          {
            titleVal: "S",
            valueVal: "S",
          },
          {
            titleVal: "T",
            valueVal: "T",
          },
          {
            titleVal: "U",
            valueVal: "U",
          },
          {
            titleVal: "V",
            valueVal: "V",
          },
          {
            titleVal: "W",
            valueVal: "W",
          },
          {
            titleVal: "X",
            valueVal: "X",
          },
          {
            titleVal: "Y",
            valueVal: "Y",
          },
          {
            titleVal: "Z",
            valueVal: "Z",
          },
          {
            titleVal: "BLACK",
            valueVal: "BLACK",
          },
        ],
        relativeTo: "menstrual_status",
        visibleRelative: "Sertifikasız",
      },
      {
        name: "berraklik",
        type: "select",
        title: "Berraklık",
        placeholder: "Berraklık Değerini Giriniz...",
        requiredMessage: "Berraklık Değeri Boş Bırakılamaz",
        required: true,
        relativeTo: "menstrual_status",
        span: 2,
        options: [
          {
            titleVal: "FL",
            valueVal: "FL",
          },
          {
            titleVal: "IF",
            valueVal: "IF",
          },
          {
            titleVal: "VVS1",
            valueVal: "VVS1",
          },
          {
            titleVal: "VVS2",
            valueVal: "VVS2",
          },
          {
            titleVal: "VS1",
            valueVal: "VS1",
          },
          {
            titleVal: "VS2",
            valueVal: "VS2",
          },
          {
            titleVal: "SI1",
            valueVal: "SI1",
          },
          {
            titleVal: "SI2",
            valueVal: "SI2",
          },
          {
            titleVal: "I1",
            valueVal: "I1",
          },
          {
            titleVal: "I2",
            valueVal: "I2",
          },
          {
            titleVal: "I3",
            valueVal: "I3",
          },
        ],
        spesificRelatedItem: "Sertifikasız",
      },
      {
        name: "berraklik2",
        type: "select",
        title: "",
        placeholder: "Berraklık Değerini Giriniz...",
        requiredMessage: "Berraklık Değeri Boş Bırakılamaz",
        required: true,
        relativeTo: "menstrual_status",
        span: 1,
        options: [
          {
            titleVal: "FL",
            valueVal: "FL",
          },
          {
            titleVal: "IF",
            valueVal: "IF",
          },
          {
            titleVal: "VVS1",
            valueVal: "VVS1",
          },
          {
            titleVal: "VVS2",
            valueVal: "VVS2",
          },
          {
            titleVal: "VS1",
            valueVal: "VS1",
          },
          {
            titleVal: "VS2",
            valueVal: "VS2",
          },
          {
            titleVal: "SI1",
            valueVal: "SI1",
          },
          {
            titleVal: "SI2",
            valueVal: "SI2",
          },
          {
            titleVal: "I1",
            valueVal: "I1",
          },
          {
            titleVal: "I2",
            valueVal: "I2",
          },
          {
            titleVal: "I3",
            valueVal: "I3",
          },
        ],
        visibleRelative: "Sertifikasız",
      },
      {
        name: "mensei",
        type: "select",
        title: "Menşei",
        span: 2,

        placeholder: "Menşei Değerini Seçiniz...",
        required: true,
        requiredMessage: "Menşei Değeri Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        // showIconRelativeTo: "Sertifikasız",
        staticOptions: MenseiList,
      },

      {
        name: "elek",
        type: "select",
        title: "Elek",
        placeholder: "Elek Değerini Giriniz...",
        required: false,
        requiredMessage: "Elek Değeri Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        visibleRelative: "Sertifikasız",
        span: 2,
        options: [
          {
            titleVal: "60",
            valueVal: "60",
          },
          {
            titleVal: "70",
            valueVal: "70",
          },
          {
            titleVal: "80",
            valueVal: "80",
          },
          {
            titleVal: "90",
            valueVal: "90",
          },
          {
            titleVal: "100",
            valueVal: "100",
          },
          {
            titleVal: "110",
            valueVal: "110",
          },
          {
            titleVal: "115",
            valueVal: "115",
          },
          {
            titleVal: "120",
            valueVal: "120",
          },
          {
            titleVal: "125",
            valueVal: "125",
          },
          {
            titleVal: "130",
            valueVal: "130",
          },
          {
            titleVal: "135",
            valueVal: "135",
          },
          {
            titleVal: "140",
            valueVal: "140",
          },
          {
            titleVal: "145",
            valueVal: "145",
          },
          {
            titleVal: "150",
            valueVal: "150",
          },
          {
            titleVal: "155",
            valueVal: "155",
          },
          {
            titleVal: "160",
            valueVal: "160",
          },
          {
            titleVal: "170",
            valueVal: "170",
          },
          {
            titleVal: "180",
            valueVal: "180",
          },
          {
            titleVal: "190",
            valueVal: "190",
          },
          {
            titleVal: "200",
            valueVal: "200",
          },
          {
            titleVal: "210",
            valueVal: "210",
          },
          {
            titleVal: "220",
            valueVal: "220",
          },
          {
            titleVal: "230",
            valueVal: "230",
          },
          {
            titleVal: "240",
            valueVal: "240",
          },
          {
            titleVal: "250",
            valueVal: "250",
          },
          {
            titleVal: "260",
            valueVal: "260",
          },
          {
            titleVal: "270",
            valueVal: "270",
          },
          {
            titleVal: "70",
            valueVal: "70",
          },
        ],
      },

      {
        name: "boy",
        type: "select",
        title: "Boy",
        span: 2,
        isCodeRelated: true,
        placeholder: "Boy Değerini Giriniz...",
        required: true,
        requiredMessage: "Boy Değeri Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        showIconRelativeTo: "Sertifikasız",
        options: PirlantaBoyKodlari,
      },

      {
        name: "aciklama",
        type: "text",
        title: "Açıklama",
        placeholder: "Açıklama Değerini Giriniz...",
        relativeTo: "menstrual_status",
        required: false,
        requiredMessage: "Açıklama Değeri Boş Bırakılamaz",
        span: 4,
      },
      // {
      //   name: "sertifikaResim",
      //   type: "file",
      //   title: "Sertifika",
      //   placeholder: "Sertifika Resim Seçiniz...",
      //   required: true,
      //   requiredMessage: "Sertifika Resmi Seçiniz",
      //   relativeTo: "menstrual_status",
      //   span: 4,
      //   visibleRelative: "Sertifikalı",
      // },
    ],
  },
  {
    visibleRelativeColumn: "menstrual_status",
    colsLenght: "12",
    visibleRelativeToValue: "Sertifikalı",
    sectionTitle: "Sertifika Bilgileri",
    groupNumber: 1,
    keyString: "product_certificate",
    elements: [
      {
        name: "sertifika",
        type: "select",
        title: "Sertifika",
        placeholder: "Sertifika Seçiniz...",
        required: false,
        span: 4,
        requiredMessage: "Kesim Değerini Boş Bırakılamaz",
        options: [
          {
            titleVal: "HRD",
            valueVal: "HRD",
          },
          {
            titleVal: "GIA",
            valueVal: "GIA",
          },
          {
            titleVal: "NONE",
            valueVal: "NONE",
          },
        ],
      },

      {
        name: "sertifikaNo",
        type: "text",
        relativeTo: "sertifika",
        title: "Sertifika No",
        placeholder: "Sertifika No Değerini Giriniz...",
        required: true,
        requiredMessage: "Sertifika No Değeri Boş Bırakılamaz",
        disabled: true,
        span: 4,
      },
      {
        name: "sertifikaTarihi",
        type: "datepicker",
        title: "Sertifika Tarihi",
        placeholder: "Sertifika Tarihi Değerini Giriniz...",
        required: true,
        requiredMessage: "Sertifika Tarihi Değeri Boş Bırakılamaz",
        disabled: true,
        relativeTo: "sertifika",
        span: 4,
      },
      {
        name: "propotion",
        type: "select",
        title: "Propotion",
        placeholder: "Propotion Seçiniz...",
        required: true,
        disabled: true,
        span: 3,
        relativeTo: "sertifika",
        requiredMessage: "Propotion Değerini Boş Bırakılamaz",
        options: [
          {
            titleVal: "EXC",
            valueVal: "EXC",
          },
          {
            titleVal: "VG",
            valueVal: "VG",
          },
          {
            titleVal: "F",
            valueVal: "F",
          },
          {
            titleVal: "P",
            valueVal: "P",
          },
          {
            titleVal: "-",
            valueVal: "-",
          },
        ],
      },
      {
        name: "polish",
        type: "select",
        title: "Polish",
        relativeTo: "sertifika",
        placeholder: "Polish Seçiniz...",
        required: true,
        disabled: true,
        requiredMessage: "Polish Değerini Boş Bırakılamaz",
        span: 3,
        options: [
          {
            titleVal: "EXC",
            valueVal: "EXC",
          },
          {
            titleVal: "VG",
            valueVal: "VG",
          },
          {
            titleVal: "F",
            valueVal: "F",
          },
          {
            titleVal: "P",
            valueVal: "P",
          },
        ],
      },
      {
        name: "symmetry",
        type: "select",
        title: "Symmetry",
        placeholder: "Symmetry Seçiniz...",
        required: true,
        disabled: true,
        relativeTo: "sertifika",
        span: 3,
        requiredMessage: "Symmetry Değerini Boş Bırakılamaz",
        options: [
          {
            titleVal: "EXC",
            valueVal: "EXC",
          },
          {
            titleVal: "VG",
            valueVal: "VG",
          },
          {
            titleVal: "F",
            valueVal: "F",
          },
          {
            titleVal: "P",
            valueVal: "P",
          },
        ],
      },
      {
        name: "fluorescence",
        type: "select",
        title: "Fluorescence",
        placeholder: "Fluorescence Seçiniz...",
        required: true,
        relativeTo: "sertifika",
        span: 3,
        disabled: true,
        requiredMessage: "Fluorescence Değerini Boş Bırakılamaz",
        options: [
          {
            titleVal: "NONE",
            valueVal: "NONE",
          },
          {
            titleVal: "FAINT",
            valueVal: "FAINT",
          },
          {
            titleVal: "MEDIUM",
            valueVal: "MEDIUM",
          },
          {
            titleVal: "STRONG",
            valueVal: "STRONG",
          },
          {
            titleVal: "SLIGHT",
            valueVal: "SLIGHT",
          },
        ],
      },
      {
        name: "min",
        type: "number",
        title: "Min",
        placeholder: "Min  Değerini Giriniz...",
        required: true,
        relativeTo: "sertifika",
        requiredMessage: "Min Değeri Boş Bırakılamaz",
        disabled: true,
        span: 4,
      },
      {
        name: "max",
        type: "number",
        title: "Max",
        placeholder: "Max Değerini Giriniz...",
        required: true,
        requiredMessage: "Max Değeri Boş Bırakılamaz",
        disabled: true,
        relativeTo: "sertifika",
        span: 4,
      },
      {
        name: "height",
        type: "number",
        title: "Height",
        placeholder: "Height Değerini Giriniz...",
        required: true,
        relativeTo: "sertifika",
        requiredMessage: "Height Değeri Boş Bırakılamaz",
        disabled: true,
        span: 4,
      },
      {
        name: "table",
        type: "number",
        title: "Table",
        placeholder: "Table Değerini Giriniz...",
        required: true,
        requiredMessage: "Table Değeri Boş Bırakılamaz",
        disabled: true,
        relativeTo: "sertifika",
        span: 4,
        rightIcon: "%",
      },
      {
        name: "totalDepth",
        type: "number",
        title: "Total Depth",
        placeholder: "Total Depth Değerini Giriniz...",
        required: true,
        requiredMessage: "Total Depth Değeri Boş Bırakılamaz",
        disabled: true,
        relativeTo: "sertifika",
        span: 4,
        rightIcon: "%",
      },
      {
        name: "girdle",
        type: "number",
        title: "Girdle",
        placeholder: "Girdle Değerini Giriniz...",
        required: true,
        relativeTo: "sertifika",
        requiredMessage: "Girdle Değeri Boş Bırakılamaz",
        disabled: true,
        span: 4,
      },
      {
        name: "sertifikaDosyasi",
        type: "file",
        relativeTo: "sertifika",
        title: "Sertifika Dosyası",
        placeholder: "Sertifika Dosyası Seçiniz...",
        required: false,
        requiredMessage: "Sertifika No Değeri Boş Bırakılamaz",
        disabled: true,
        span: 4,
      },
    ],
  },
  {
    colsLenght: "4",
    sectionTitle: "Pırlanta Fiyat Bilgileri",
    groupNumber: 1,
    keyString: "product_cost",
    elements: [
      {
        name: "buy_date",
        type: "datepicker",
        title: "Satin Alma Tarihi",
        placeholder: "Satın Alma Tarihi Değerini Giriniz...",
        required: true,
        requiredMessage: "Satın Alma Tarihi Değerini Boş Bırakılamaz",
        span: 1,
      },
      {
        name: "rapaportPrice",
        type: "text",
        title: "Rapaport Güncel Fiyatı",
        placeholder: "Rapaport Güncel Fiyatı...",
        required: true,
        requiredMessage: "Karat Değeri Boş Bırakılamaz",
        disabled: true,
        rightIcon: "$",
        value: "2500",
        isCurrency: true,
        span: 1,
        // relativeTo: "menstrual_status",
        // visibleRelative: "Sertifikalı",
      },
      {
        name: "iskonto",
        type: "number",
        title: "İskonto",
        placeholder: "İskonto...",
        required: true,
        requiredMessage: "İskonto Boş Bırakılamaz",
        span: 1,
        rightIcon: "$",
        // relativeTo: "menstrual_status",
        // visibleRelative: "Sertifikalı",
      },
      {
        name: "pricePerCarat",
        type: "text",
        title: "Price Per Carat",
        placeholder: "Price Per Carat...",
        required: false,
        requiredMessage: "İskonto Boş Bırakılamaz",
        disabled: true,
        isCurrency: true,
        rightIcon: "$",
        span: 1,
      },
      {
        name: "total_cost",
        type: "text",
        title: "Toplam Fiyat",
        placeholder: "Toplam Fiyat...",
        required: false,
        requiredMessage: "Toplam Fiyat Bırakılamaz",
        disabled: true,
        isCurrency: true,
        rightIcon: "$",
        colStart: "4",
        colEnd: "5",
        span: 1,
      },
    ],
  },
];

export const SadeModelTurleri: CustomOptionType[] = [
  {
    titleVal: "Alyans",
    valueVal: "Alyans",
    extraValue: "ALY",
  },
  {
    titleVal: "Bileklik",
    valueVal: "Bileklik",
    extraValue: "BL",
  },
  {
    titleVal: "Kelepçe",
    valueVal: "Kelepçe",
    extraValue: "BNG",
  },
  {
    titleVal: "Broş",
    valueVal: "Broş",
    extraValue: "BRS",
  },
  {
    titleVal: "Kol Düğmesi",
    valueVal: "Kol Düğmesi",
    extraValue: "CF",
  },
  {
    titleVal: "Küpe",
    valueVal: "Küpe",
    extraValue: "E",
  },
  {
    titleVal: "Anturaj Küpe",
    valueVal: "Anturaj Küpe",
    extraValue: "EA",
  },
  {
    titleVal: "Küpe Arkalığı",
    valueVal: "Küpe Arkalığı",
    extraValue: "EK",
  },
  {
    titleVal: "Tektaş Küpe",
    valueVal: "Tektaş Küpe",
    extraValue: "ES",
  },
  {
    titleVal: "Bilezik",
    valueVal: "Bilezik",
    extraValue: "FBR",
  },
  {
    titleVal: "Kilit",
    valueVal: "Kilit",
    extraValue: "KLT",
  },
  {
    titleVal: "Erkek Yüzüğü",
    valueVal: "Erkek Yüzüğü",
    extraValue: "MR",
  },
  {
    titleVal: "Gerdanlık",
    valueVal: "Gerdanlık",
    extraValue: "NEC",
  },
  {
    titleVal: "Zincirli Kolye",
    valueVal: "Zincirli Kolye",
    extraValue: "NZ",
  },
  {
    titleVal: "Kolye Ucu",
    valueVal: "Kolye Ucu",
    extraValue: "P",
  },
  {
    titleVal: "Anturaj Kolye Ucu",
    valueVal: "Anturaj Kolye Ucu",
    extraValue: "PA",
  },
  {
    titleVal: "Tektaş Kolye ucu",
    valueVal: "Tektaş Kolye ucu",
    extraValue: "PS",
  },
  {
    titleVal: "Anturaj Yüzük",
    valueVal: "Anturaj Yüzük",
    extraValue: "RA",
  },
  {
    titleVal: "Genel Fantazi Yüzük",
    valueVal: "Genel Fantazi Yüzük",
    extraValue: "RF",
  },
  {
    titleVal: "Tektaş Yüzük",
    valueVal: "Tektaş Yüzük",
    extraValue: "RS",
  },
  {
    titleVal: "Tamtur Yüzük",
    valueVal: "Tamtur Yüzük",
    extraValue: "RTT",
  },
  {
    titleVal: "Zincirler",
    valueVal: "Zincirler",
    extraValue: "RULO",
  },
  {
    titleVal: "Rozet",
    valueVal: "Rozet",
    extraValue: "RZ",
  },

  {
    titleVal: "Takım Bileklik",
    valueVal: "Takım Bileklik",
    extraValue: "TKB",
  },
  {
    titleVal: "Takım Küpe",
    valueVal: "Takım Küpe",
    extraValue: "TKY",
  },
  {
    titleVal: "Takım Kolye",
    valueVal: "Takım Kolye",
    extraValue: "TKP",
  },
  {
    titleVal: "Takım Yüzük",
    valueVal: "Takım Yüzük",
    extraValue: "TKR",
  },
  {
    titleVal: "Tespih",
    valueVal: "Tespih",
    extraValue: "TS",
  },
  {
    titleVal: "Beş Taş Yüzük",
    valueVal: "Beş Taş Yüzük",
    extraValue: "WR",
  },

  {
    titleVal: "Zincir",
    valueVal: "Zincir",
    extraValue: "ZN",
  },
];

export const AddRenkliTasSections: Array<FormSectionType> = [
  {
    colsLenght: "8",
    sectionTitle: "Renkli Taş Bilgileri",
    groupNumber: 0,
    keyString: "properties",
    extraElementRelativeTo: "menstrual_status",
    extraElementVisibleRelative: "Sertifikalı",
    extraElements: [
      {
        name: "fromsingleormixed",
        type: "customButtonGroup",
        isCodeRelated: true,
        title: "Tip",
        checkBoxList: ["From Single", "From Mixed"],
        required: true,
        requiredMessage: "Karat Değeri Boş Bırakılamaz",
        checkBoxSetValueItem: "fromsingleormixed",
        span: 4,
        value: "From Single",
      },
      {
        name: "frommixedItem",
        type: "select",
        title: "Mixed Grubu",
        isCodeRelated: true,
        required: true,
        requiredMessage: "Kesim Değerini Boş Bırakılamaz",
        relativeTo: "fromsingleormixed",
        visibleRelative: "From Mixed",
        isExtra: true,
        span: 4,
      },
    ],
    elements: [
      {
        name: "menstrual_status",
        isCodeRelated: true,
        type: "customButtonGroup",
        checkBoxList: ["Sertifikalı", "Sertifikasız"],
        required: true,
        requiredMessage: "Karat Değeri Boş Bırakılamaz",
        checkBoxSetValueItem: "menstrual_status",
        span: 8,
      },
      {
        name: "renkliTas",
        type: "select",
        isCodeRelated: true,
        title: "Renkli Taş",
        placeholder: "Renkli Taş Seçiniz...",
        required: true,
        requiredMessage: "Renkli Taş Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        span: 2,
        options: RenkliTasListesiData,
      },
      {
        name: "carat",
        type: "number",
        title: "Karat",
        placeholder: "Karat Değerini Giriniz...",
        required: true,
        requiredMessage: "Karat Değeri Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        span: 2,
        // simgeturu: "caratType",
      },
      {
        name: "renk",
        type: "select",
        title: "Renk",
        placeholder: "Renk Seçiniz...",
        required: true,
        requiredMessage: "Renk Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        span: 2,
        options: RenkliTasRenkListesi,
      },
      {
        name: "kesim",
        type: "select",
        title: "Kesim",
        placeholder: "Kesim Değerini Giriniz...",
        required: true,
        requiredMessage: "Kesim Değerini Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        span: 2,
        options: [
          {
            titleVal: "ROUND",
            valueVal: "ROUND",
          },
          {
            titleVal: "HEART",
            valueVal: "HEART",
          },
          {
            titleVal: "PEAR",
            valueVal: "PEAR",
          },
          {
            titleVal: "MARQUISE",
            valueVal: "MARQUISE",
          },
          {
            titleVal: "OVAL",
            valueVal: "OVAL",
          },
          {
            titleVal: "BAGET",
            valueVal: "BAGET",
          },
          {
            titleVal: "TRAPEZ",
            valueVal: "TRAPEZ",
          },
          {
            titleVal: "TRIANGLE",
            valueVal: "TRIANGLE",
          },
          {
            titleVal: "PRENSES",
            valueVal: "PRENSES",
          },
          {
            titleVal: "RADIANT",
            valueVal: "RADIANT",
          },
          {
            titleVal: "EMERALD",
            valueVal: "EMERALD",
          },
          {
            titleVal: "CUSHION",
            valueVal: "CUSHION",
          },
          {
            titleVal: "CABOCHON",
            valueVal: "CABOCHON",
          },
        ],
      },
      {
        name: "mensei",
        type: "select",
        title: "Menşei",
        placeholder: "Menşei Seçiniz...",
        required: false,
        requiredMessage: "Menşei Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        span: 2,
        staticOptions: MenseiList,
      },
      {
        name: "treatment",
        type: "select",
        title: "Treatment",
        placeholder: "Treatment Seçiniz...",
        required: false,
        requiredMessage: "Treatment Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        span: 2,
        options: [
          {
            titleVal: "HEATED",
            valueVal: "HEATED",
          },
          {
            titleVal: "NOT HEATED",
            valueVal: "NOT HEATED",
          },
        ],
      },
      {
        name: "pricePerCarat",
        type: "text",
        title: "Price Per Carat",
        placeholder: "Price Per Carat...",
        required: true,
        requiredMessage: "Karat Başına Maliyet Giriniz",
        isCurrency: true,
        rightIcon: "$",
        disabled: true,
        span: 2,
      },
      {
        name: "total_cost",
        type: "number",
        title: "Toplam Fiyat",
        placeholder: "Toplam Fiyat...",
        required: true,
        requiredMessage: "Toplam Fiyat Boş Bırakılamaz",
        disabled: false,
        rightIcon: "$",
        span: 2,
      },
      {
        name: "sertifikaDosyasi",
        type: "file",
        title: "Sertifika Dosyası",
        placeholder: "Sertifika Dosyası Seçiniz...",
        required: false,
        requiredMessage: "Sertifika Dosyası  Boş Bırakılamaz",
        disabled: true,
        span: 2,
        relativeTo: "menstrual_status",
        visibleRelative: "Sertifikalı",
      },
    ],
  },
];
