import { FormSectionType } from "../../types/formTypes";
import { FaGlobe } from "react-icons/fa6";

import {
  AltinAyarData,
  AltinRengiData,
  AtolyeListesi,
  SadeModelTurleri,
} from "@/data/Sade.data";
import {
  PirlantaBerraklikData,
  PirlantaBoyKodlari,
  PirlantaElekData,
  PirlantaKesimKodlariData,
  PirlantaRenkData,
} from "@/data/Pirlanta.data";
import {
  RenkliTasListesiData,
  RenkliTasListesiKesimData,
  RenkliTasListesiMenseiList,
  RenkliTasRenkListesi,
} from "@/data/RenkliTas.data";
import { GenerateSertificateUrl } from "./Pirlanta.Utils";
import { CustomOptionType } from "../../types/inputTypes";
import { TedarikciCustomListType } from "./Tedarikciler.Utils";
export const PirlantaSertifikaKodlari: CustomOptionType[] = [
  {
    titleVal: "HRD",
    valueVal: "HRD",
  },
  {
    titleVal: "GIA",
    valueVal: "GIA",
  },
  {
    titleVal: "NONE",
    valueVal: "NONE",
  },
  {
    titleVal: "IGI",
    valueVal: "IGI",
  },
  {
    titleVal: "ANL",
    valueVal: "ANL",
  },
];

export const RenkliTasSertifikaKodlari: CustomOptionType[] = [
  {
    titleVal: "HRD",
    valueVal: "HRD",
  },
  {
    titleVal: "GIA",
    valueVal: "GIA",
  },
  {
    titleVal: "NONE",
    valueVal: "NONE",
  },
  {
    titleVal: "GIL",
    valueVal: "GIL",
  },
  {
    titleVal: "GRS",
    valueVal: "GRS",
  },
  {
    titleVal: "AGL",
    valueVal: "AGL",
  },
  {
    titleVal: "GFCO",
    valueVal: "GFCO",
  },
  {
    titleVal: "IGSL",
    valueVal: "IGSL",
  },
  {
    titleVal: "IGI",
    valueVal: "IGI",
  },
  {
    titleVal: "GFC",
    valueVal: "GFC",
  },
];

export const AddSadeSections: Array<FormSectionType> = [
  {
    colsLenght: "12",
    sectionTitle: "Sade Bilgileri",
    groupNumber: 0,
    keyString: "properties",
    elements: [
      {
        name: "type",
        type: "customButtonGroup",
        title: "Tip",
        checkBoxList: ["Stok", "Sipariş"],
        required: true,
        requiredMessage: "Karat Değeri Boş Bırakılamaz",
        checkBoxSetValueItem: "type",
        isCodeRelated: true,
        span: 12,
      },
      {
        name: "resim",
        type: "file",
        title: "Ürün Görseli",
        placeholder: "Sade Ürün Görseli Seçiniz...",
        required: true,
        requiredMessage: "Sade Ürün Görseli Seçiniz",
        relativeTo: "type",
        span: 3,
        rowSpan: 5,
        showPicture: true,
        pictureExtraText: "PNG,JPG (MAX 3MB)",
      },

      {
        name: "sadeKodu",
        type: "text",
        title: "Sade Kodu",
        disabled: true,
        placeholder: "Sade Kodu Giriniz...",
        required: true,
        requiredMessage: "Sade Kodu Değeri Boş Bırakılamaz",
        span: 3,
      },
      {
        name: "modelTuru",
        type: "select",
        title: "Model Türü",
        placeholder: "Model Türü Giriniz...",
        required: true,
        requiredMessage: "Model Türü Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
        options: SadeModelTurleri,
      },
      {
        name: "modelKodu",
        type: "text",
        title: "Model Kodunu Giriniz",
        placeholder: "Model Kodu Giriniz...",
        required: true,
        requiredMessage: "Model Kodu Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
        extraValidations: {
          maxLength: {
            value: 4,
            message: "Model Kodu 4 Haneden Oluşmalıdır ",
          },
          minLength: {
            value: 4,
            message: "Model Kodu 4 Haneden Oluşmalıdır",
          },
        },
      },
      {
        name: "atolye",
        type: "select",
        title: "Atölye Seçiniz",
        placeholder: "Atölye Giriniz...",
        required: true,
        requiredMessage: "Atölye Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
        options: AtolyeListesi,
      },
      {
        name: "iscilik",
        type: "money",
        title: "İşçilik",
        placeholder: "İşçilik Giriniz...",
        required: true,
        requiredMessage: "İşçilik Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 2,
      },
      {
        name: "cost_currency",
        type: "select",
        title: "Birim",
        placeholder: "Birim Giriniz...",
        required: true,
        requiredMessage: "Birim Değeri Boş Bırakılamaz",
        relativeTo: "type",
        options: [
          { titleVal: "HAS", valueVal: "HAS" },
          { titleVal: "USD", valueVal: "USD" },
        ],
        span: 1,
      },
      {
        name: "altinRengi",
        type: "select",
        title: "Altın Rengi",
        placeholder: "Altın Rengi Giriniz...",
        required: true,
        requiredMessage: "Altın Rengi Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
        options: AltinRengiData,
      },
      {
        name: "gram",
        type: "number",
        title: "Gram",
        placeholder: "Gram Giriniz...",
        required: true,
        requiredMessage: "Gram Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
      },
      {
        name: "ayar",
        type: "select",
        title: "Ayar",
        placeholder: "Ayar Giriniz...",
        required: true,
        requiredMessage: "Ayar Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
        options: AltinAyarData,
      },
      {
        name: "hasGrami",
        type: "text",
        title: "Has Gramı",
        placeholder: "Has Gramı Giriniz...",
        required: true,
        requiredMessage: "Has Gramı Değeri Boş Bırakılamaz",
        disabled: true,
        span: 3,
      },
      {
        name: "aciklama",
        type: "text",
        title: "Açıklama",
        placeholder: "Açıklama Giriniz...",
        required: false,
        requiredMessage: "Açıklama Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
        rowSpan: 2,
        colStart: "4",
        colEnd: "10",
      },
      {
        name: "girisTarihi",
        type: "datepicker",
        title: "Giriş Tarihi",
        placeholder: "Giriş Tarihi Giriniz...",
        required: true,
        requiredMessage: "Giriş Tarihi Değeri Boş Bırakılamaz",
        relativeTo: "type",
        span: 3,
      },
    ],
  },
];

export const AddTedarikciSections: Array<FormSectionType> = [
  {
    colsLenght: "8",
    sectionTitle: "Tedarikçi Bilgileri",
    groupNumber: 0,
    keyString: "infoSection1",
    elements: [
      {
        name: "code",
        type: "text",
        title: "Tedarikçi Kodu",
        placeholder: "Tedarikçi Kodu Giriniz...",
        required: true,
        requiredMessage: "Tedarikçi Kodu Boş Bırakılamaz",
        span: 2,
      },
      {
        name: "name",
        type: "text",
        title: "Tedarikçi Adı",
        placeholder: "Tedarikçi Adı Giriniz...",
        required: true,
        requiredMessage: "Tedarikçi Adı Boş Bırakılamaz",
        span: 2,
      },
      {
        name: "phone",
        type: "tel",
        title: "Tedarikçi Telefonu",
        placeholder: "Tedarikçi Telefonu Giriniz...",
        required: true,
        requiredMessage: "Tedarikçi Telefonu Boş Bırakılamaz",
        span: 2,
      },
      {
        name: "e_mail",
        type: "email",
        title: "Tedarikçi E-Posta",
        placeholder: "Tedarikçi E-Posta Giriniz...",
        required: true,
        requiredMessage: "Tedarikçi E-Posta Boş Bırakılamaz",
        span: 2,
        extraValidations: {
          pattern: {
            value: /\S+@\S+\.\S+/,
            message: "E-Posta Format/Yazım Hatası!",
          },
        },
      },
      {
        name: "area",
        type: "radiobuttonlist",
        title: "Tedarikçi Tipi",
        checkBoxList: ["Domestic", "Foreign"],
        required: true,
        span: 2,
      },
      {
        name: "address",
        type: "textarea",
        title: "Tedarikçi Adres",
        placeholder: "Tedarikçi Adres Giriniz Giriniz...",
        required: true,
        requiredMessage: "Tedarikçi Adres Boş Bırakılamaz",
        span: 6,
        colStart: "3",
        colEnd: "9",
      },
    ],
  },
  {
    colsLenght: "8",
    sectionTitle: "Tedarikçi Bilgileri",
    groupNumber: 0,
    keyString: "infoSection2",
    elements: [
      {
        name: "currenc_code",
        type: "text",
        title: "Cari Kodu",
        placeholder: "Cari Kodunu Giriniz...",
        required: true,
        requiredMessage: "Tedarikçi Cari Kodu Boş Bırakılamaz",
        span: 2,
      },
      {
        name: "tax_number",
        type: "text",
        title: "Vergi No",
        placeholder: "Vergi No Giriniz...",
        required: true,
        requiredMessage: "Vergi No Boş Bırakılamaz",
        span: 2,
        maxLenghtCondition: {
          field: "area",
          property: "Domestic",
          maxLenght: 11,
        },
      },
      {
        name: "bank",
        type: "text",
        title: "Banka",
        placeholder: "Banka Giriniz...",
        required: true,
        requiredMessage: "Tedarikçi Banka Boş Bırakılamaz",
        span: 2,
      },
    ],
  },
  {
    colsLenght: "8",
    sectionTitle: "Tedarikçi Yetkili Bilgileri",
    groupNumber: 0,
    keyString: "infoSection3",
    elements: [
      {
        name: "authorized_name",
        type: "text",
        title: "Yetkili Ad/Soyad",
        placeholder: "Yetkili Ad Soyad Giriniz...",
        required: true,
        requiredMessage: "Yetkili Ad/Soyad Boş Bırakılamaz",
        span: 2,
      },
      {
        name: "authorized_phone",
        type: "tel",
        title: "Yetkili Telefonu",
        placeholder: "Yetkili Telefonu Giriniz...",
        required: true,
        requiredMessage: "Yetkili Telefonu Boş Bırakılamaz",
        span: 2,
      },
      {
        name: "authorized_e_mail",
        type: "email",
        title: "Yetkili E-Posta",
        placeholder: "Yetkili E-Posta Giriniz...",
        required: true,
        requiredMessage: "Yetkili E-Posta Boş Bırakılamaz",
        span: 2,
        extraValidations: {
          pattern: {
            value: /\S+@\S+\.\S+/,
            message: "E-Posta Format/Yazım Hatası!",
          },
        },
      },
    ],
  },
];

export const AddMusteriSections: Array<FormSectionType> = [
  {
    colsLenght: "8",
    sectionTitle: "Müşteri Bilgileri",
    groupNumber: 0,
    keyString: "infoSection1",
    elements: [
      {
        name: "code",
        type: "text",
        title: "Müşteri Kodu",
        placeholder: "Müşteri Kodu Giriniz...",
        required: true,
        requiredMessage: "Müşteri Kodu Boş Bırakılamaz",
        span: 2,
      },
      {
        name: "name",
        type: "text",
        title: "Müşteri Adı",
        placeholder: "Müşteri Adı Giriniz...",
        required: true,
        requiredMessage: "Müşteri Adı Boş Bırakılamaz",
        span: 2,
      },
      {
        name: "phone",
        type: "tel",
        title: "Müşteri Telefonu",
        placeholder: "Müşteri Telefonu Giriniz...",
        required: true,
        requiredMessage: "Müşteri Telefonu Boş Bırakılamaz",
        span: 2,
      },
      {
        name: "e_mail",
        type: "email",
        title: "Müşteri E-Posta",
        placeholder: "Müşteri E-Posta Giriniz...",
        required: true,
        requiredMessage: "Müşteri E-Posta Boş Bırakılamaz",
        span: 2,
        extraValidations: {
          pattern: {
            value: /\S+@\S+\.\S+/,
            message: "E-Posta Format/Yazım Hatası!",
          },
        },
      },
      {
        name: "area",
        type: "radiobuttonlist",
        title: "Müşteri Tipi",
        checkBoxList: ["Domestic", "Foreign"],
        required: true,
        span: 2,
      },
      {
        name: "invoice_address",
        type: "textarea",
        title: "Müşteri Fatura Adresi",
        placeholder: "Müşteri Fatura Adresi Giriniz...",
        required: false,
        rows: 4,
        requiredMessage: "Müşteri Fatura Adres Boş Bırakılamaz",
        span: 4,
        colStart: "3",
        colEnd: "6",
      },
      {
        name: "shipping_address",
        type: "textarea",
        title: "Müşteri Gönderim Adresi",
        placeholder: "Müşteri Gönderim Adresi Giriniz...",
        required: false,
        rows: 4,
        requiredMessage: "Müşteri Gönderim Adresi Boş Bırakılamaz",
        span: 4,
        colStart: "6",
        colEnd: "9",
      },
      {
        name: "country_code",
        type: "select",
        title: "Ülke Seçiniz",
        placeholder: "Ülke Seçiniz...",
        required: false,
        requiredMessage: "Ülke Seçiniz",
        span: 2,
        relativeTo: "area",
        visibleRelative: "Foreign",
        staticOptions: RenkliTasListesiMenseiList,
        moveToTop: true,
      },
    ],
  },
  {
    colsLenght: "8",
    sectionTitle: "Müşteri Bilgileri",
    groupNumber: 0,
    keyString: "infoSection2",
    visibleRelativeColumn: "area",
    visibleRelativeToValue: "Foreign",
    elements: [
      {
        name: "company_type",
        type: "select",
        title: "Şirket Türü",
        placeholder: "Şirket Türü Seçiniz",
        required: false,
        requiredMessage: "Şirket Türü Seçiniz",
        span: 2,
      },
      {
        name: "company_foundation_date",
        type: "datepicker",
        title: "Şirket Kuruluş Tarihi",
        placeholder: "Şirket Kuruluş Tarihi Giriniz...",
        required: true,
        requiredMessage: "Şirket Kuruluş Tarihi Boş Bırakılamaz",
        span: 2,
      },
      {
        name: "tax_number",
        type: "text",
        title: "Vergi No",
        placeholder: "Vergi No Giriniz...",
        required: true,
        requiredMessage: "Vergi No Boş Bırakılamaz",
        span: 2,
      },
      {
        name: "bank",
        type: "text",
        title: "Banka",
        placeholder: "Banka Giriniz...",
        required: true,
        requiredMessage: "Şirket Banka Boş Bırakılamaz",
        span: 2,
      },
      {
        name: "chamber_of_commerce",
        type: "text",
        title: "Meslek Odası",
        placeholder: "Meslek Odası Giriniz...",
        required: true,
        requiredMessage: "Meslek Odası Boş Bırakılamaz",
        span: 2,
      },
      {
        name: "company_sector",
        type: "text",
        title: "Şirket Sektörü",
        placeholder: "Şirket Sektörü Giriniz...",
        required: true,
        requiredMessage: "Şirket Sektörü Boş Bırakılamaz",
        span: 2,
      },
      {
        name: "sector_year",
        type: "number",
        title: "Sektör Yılı",
        placeholder: "Sektör Yılı Giriniz...",
        required: true,
        requiredMessage: "Sektör Yılı Boş Bırakılamaz",
        span: 2,
      },
      {
        name: "posta_kodu",
        type: "text",
        title: "Posta Kodu",
        placeholder: "Posta Kodu Giriniz...",
        required: true,
        requiredMessage: "Posta Kodu Boş Bırakılamaz",
        span: 2,
      },
    ],
  },
  {
    colsLenght: "8",
    sectionTitle: "Banka Bilgileri",
    groupNumber: 0,
    keyString: "infoSection4",
    visibleRelativeColumn: "area",
    visibleRelativeToValue: "Foreign",
    elements: [
      {
        name: "banka_adi",
        type: "text",
        title: "Banka Adı",
        placeholder: "Banka Adı Giriniz",
        required: false,
        requiredMessage: "Banka Adı Giriniz",
        span: 2,
      },
      {
        name: "banka_adresi",
        type: "text",
        title: "Banka Adresi",
        placeholder: "Banka Adresi Giriniz",
        required: false,
        requiredMessage: "Banka Adresi Giriniz",
        span: 2,
      },
      {
        name: "hesap_no",
        type: "text",
        title: "Hesap No",
        placeholder: "Hesap No Giriniz",
        required: false,
        requiredMessage: "Hesap No Giriniz",
        span: 2,
      },
      {
        name: "iban",
        type: "text",
        title: "IBAN",
        placeholder: "IBAN Giriniz",
        required: false,
        requiredMessage: "IBAN Giriniz",
        span: 2,
      },
      {
        name: "swift_code",
        type: "text",
        title: "Swift Code",
        placeholder: "Swift Code Giriniz",
        required: false,
        requiredMessage: "Swift Code Giriniz",
        span: 2,
      },
    ],
  },
  {
    colsLenght: "8",
    sectionTitle: "Müşteri Yetkili Bilgileri",
    groupNumber: 0,
    keyString: "infoSection3",
    elements: [
      {
        name: "authorized_name",
        type: "text",
        title: "Yetkili Ad/Soyad",
        placeholder: "Yetkili Ad Soyad Giriniz...",
        required: true,
        requiredMessage: "Yetkili Ad/Soyad Boş Bırakılamaz",
        span: 2,
      },
      {
        name: "authorized_phone",
        type: "tel",
        title: "Yetkili Telefonu",
        placeholder: "Yetkili Telefonu Giriniz...",
        required: true,
        requiredMessage: "Yetkili Telefonu Boş Bırakılamaz",
        span: 2,
      },
      {
        name: "authorized_e_mail",
        type: "email",
        title: "Yetkili E-Posta",
        placeholder: "Yetkili E-Posta Giriniz...",
        required: true,
        requiredMessage: "Yetkili E-Posta Boş Bırakılamaz",
        span: 2,
        extraValidations: {
          pattern: {
            value: /\S+@\S+\.\S+/,
            message: "E-Posta Format/Yazım Hatası!",
          },
        },
      },
    ],
  },
];

export const AddStoneSections: Array<FormSectionType> = [
  {
    colsLenght: "8",
    sectionTitle: "Pırlanta Bilgileri",
    groupNumber: 0,
    keyString: "properties",
    extraElementRelativeTo: "menstrual_status",
    extraElementVisibleRelative: "Sertifikalı",
    extraElements: [
      {
        name: "fromsingleormixed",
        type: "radiobuttonlist",
        title: "",
        checkBoxList: ["From Single", "From Mixed"],
        required: true,
        requiredMessage: "Karat Değeri Boş Bırakılamaz",
        checkBoxSetValueItem: "fromsingleormixed",
        span: 4,
        value: "From Single",
        isCodeRelated: true,
        mt: 12,
      },
      {
        name: "frommixedItem",
        type: "select",
        title: "Mixed Grubu",
        required: true,
        requiredMessage: "Kesim Boş Bırakılamaz",
        relativeTo: "fromsingleormixed",
        visibleRelative: "From Mixed",
        isExtra: true,
        isCodeRelated: true,
        span: 4,
      },
    ],
    elements: [
      {
        name: "menstrual_status",
        type: "customButtonGroup",
        checkBoxList: ["Sertifikalı", "Sertifikasız"],
        required: true,
        requiredMessage: "Karat Değeri Boş Bırakılamaz",
        checkBoxSetValueItem: "menstrual_status",
        span: 8,
        isCodeRelated: true,
      },
      {
        name: "kesim",
        type: "select",
        title: "Kesim",
        placeholder: "Kesim Giriniz...",
        required: true,
        requiredMessage: "Kesim Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        isCodeRelated: true,
        options: PirlantaKesimKodlariData,
        span: 2,
      },
      {
        name: "carat",
        type: "number",
        title: "Karat",
        placeholder: "Karat Giriniz...",
        required: true,
        requiredMessage: "Karat Değeri Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        span: 2,
        simgeturu: "caratType",
        showIconRelativeTo: "Sertifikalı",
      },
      {
        name: "renk",
        type: "select",
        title: "Renk",
        placeholder: "Renk Giriniz...",
        required: true,
        requiredMessage: "Renk Değeri Boş Bırakılamaz",
        options: PirlantaRenkData,
        relativeTo: "menstrual_status",
        span: 2,
        spesificRelatedItem: "Sertifikasız",
        titleRelativeField: "menstrual_status",
        titleRelativeValue: "Sertifikasız",
        secondTitle: "Renk Aralığı",
      },
      {
        name: "renk2",
        type: "select",
        title: "",
        placeholder: "Renk Giriniz...",
        required: true,
        requiredMessage: "Renk Değeri Boş Bırakılamaz",
        span: 1,
        options: PirlantaRenkData,
        relativeTo: "menstrual_status",
        visibleRelative: "Sertifikasız",
        isTopMargin: true,
      },
      {
        name: "berraklik",
        type: "select",
        title: "Berraklık",
        placeholder: "Berraklık Giriniz...",
        requiredMessage: "Berraklık Değeri Boş Bırakılamaz",
        required: true,
        relativeTo: "menstrual_status",
        span: 2,
        options: PirlantaBerraklikData,
        spesificRelatedItem: "Sertifikasız",
        titleRelativeField: "menstrual_status",
        titleRelativeValue: "Sertifikasız",
        secondTitle: "Berraklık Aralığı",
      },
      {
        name: "berraklik2",
        type: "select",
        title: "",
        placeholder: "Berraklık Giriniz...",
        requiredMessage: "Berraklık Değeri Boş Bırakılamaz",
        required: true,
        relativeTo: "menstrual_status",
        span: 1,
        options: PirlantaBerraklikData,
        visibleRelative: "Sertifikasız",
        isTopMargin: true,
      },
      {
        name: "mensei",
        type: "select",
        title: "Menşei",
        span: 2,

        placeholder: "Menşei Seçiniz...",
        required: true,
        requiredMessage: "Menşei Değeri Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        // showIconRelativeTo: "Sertifikasız",
        staticOptions: RenkliTasListesiMenseiList,
      },

      {
        name: "elek",
        type: "select",
        title: "Elek",
        placeholder: "Elek Giriniz...",
        required: false,
        requiredMessage: "Elek Değeri Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        visibleRelative: "Sertifikasız",
        span: 2,
        options: PirlantaElekData,
      },

      {
        name: "boy",
        type: "select",
        title: "Boy",
        span: 2,
        isCodeRelated: true,
        placeholder: "Boy Giriniz...",
        required: true,
        requiredMessage: "Boy Değeri Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        showIconRelativeTo: "Sertifikasız",
        options: PirlantaBoyKodlari,
      },

      {
        name: "aciklama",
        type: "text",
        title: "Açıklama",
        placeholder: "Açıklama Giriniz...",
        relativeTo: "menstrual_status",
        required: false,
        requiredMessage: "Açıklama Değeri Boş Bırakılamaz",
        span: 2,
      },
      {
        name: "supplier_id",
        type: "select",
        title: "Tedarikçi",
        placeholder: "Tedarikçi Giriniz...",
        relativeTo: "menstrual_status",
        required: false,
        requiredMessage: "Tedarikçi Değeri Boş Bırakılamaz",
        span: 2,
        colStart: "10",
        colEnd: "10",
        customOptions: TedarikciCustomListType,
        isTedarikci: true,
      },
    ],
  },
  {
    visibleRelativeColumn: "menstrual_status",
    colsLenght: "12",
    visibleRelativeToValue: "Sertifikalı",
    sectionTitle: "Sertifika Bilgileri",
    groupNumber: 1,
    keyString: "product_certificate",
    elements: [
      {
        name: "sertifika",
        type: "select",
        title: "Sertifika",
        placeholder: "Sertifika Seçiniz...",
        required: false,
        span: 3,
        requiredMessage: "Kesim Boş Bırakılamaz",
        options: PirlantaSertifikaKodlari,
      },

      {
        name: "sertifikaNo",
        type: "text",
        relativeTo: "sertifika",
        title: "Sertifika No",
        placeholder: "Sertifika No Giriniz...",
        required: true,
        requiredMessage: "Sertifika No Değeri Boş Bırakılamaz",
        disabled: true,
        span: 3,
        isLinkedWithIcon: true,
        rightIcon: <FaGlobe />,
        extraFunction: GenerateSertificateUrl,
      },
      {
        name: "sertifikaTarihi",
        type: "datepicker",
        title: "Sertifika Tarihi",
        placeholder: "Sertifika Tarihi Giriniz...",
        required: true,
        requiredMessage: "Sertifika Tarihi Değeri Boş Bırakılamaz",
        disabled: true,
        relativeTo: "sertifika",
        span: 3,
      },
      {
        name: "sertifikaDosyasi",
        type: "file",
        relativeTo: "sertifika",
        title: "Sertifika Dosyası",
        placeholder: "Sertifika Dosyası Seçiniz...",
        required: false,
        requiredMessage: "Sertifika No Değeri Boş Bırakılamaz",
        disabled: true,
        span: 3,
      },
      {
        name: "propotion",
        type: "select",
        title: "Propotion",
        placeholder: "Propotion Seçiniz...",
        required: true,
        disabled: true,
        span: 3,
        relativeTo: "sertifika",
        requiredMessage: "Propotion Boş Bırakılamaz",
        options: [
          {
            titleVal: "EXC",
            valueVal: "EXC",
          },
          {
            titleVal: "VG",
            valueVal: "VG",
          },
          {
            titleVal: "F",
            valueVal: "F",
          },
          {
            titleVal: "P",
            valueVal: "P",
          },
          {
            titleVal: "-",
            valueVal: "-",
          },
        ],
      },
      {
        name: "polish",
        type: "select",
        title: "Polish",
        relativeTo: "sertifika",
        placeholder: "Polish Seçiniz...",
        required: true,
        disabled: true,
        requiredMessage: "Polish Boş Bırakılamaz",
        span: 3,
        options: [
          {
            titleVal: "EXC",
            valueVal: "EXC",
          },
          {
            titleVal: "VG",
            valueVal: "VG",
          },
          {
            titleVal: "F",
            valueVal: "F",
          },
          {
            titleVal: "P",
            valueVal: "P",
          },
        ],
      },
      {
        name: "symmetry",
        type: "select",
        title: "Symmetry",
        placeholder: "Symmetry Seçiniz...",
        required: true,
        disabled: true,
        relativeTo: "sertifika",
        span: 3,
        requiredMessage: "Symmetry Boş Bırakılamaz",
        options: [
          {
            titleVal: "EXC",
            valueVal: "EXC",
          },
          {
            titleVal: "VG",
            valueVal: "VG",
          },
          {
            titleVal: "F",
            valueVal: "F",
          },
          {
            titleVal: "P",
            valueVal: "P",
          },
        ],
      },
      {
        name: "fluorescence",
        type: "select",
        title: "Fluorescence",
        placeholder: "Fluorescence Seçiniz...",
        required: true,
        relativeTo: "sertifika",
        span: 3,
        disabled: true,
        requiredMessage: "Fluorescence Boş Bırakılamaz",
        options: [
          {
            titleVal: "NONE",
            valueVal: "NONE",
          },
          {
            titleVal: "FAINT",
            valueVal: "FAINT",
          },
          {
            titleVal: "MEDIUM",
            valueVal: "MEDIUM",
          },
          {
            titleVal: "STRONG",
            valueVal: "STRONG",
          },
          {
            titleVal: "SLIGHT",
            valueVal: "SLIGHT",
          },
        ],
      },
      {
        name: "min",
        type: "number",
        title: "Min",
        placeholder: "Min  Giriniz...",
        required: true,
        relativeTo: "sertifika",
        requiredMessage: "Min Değeri Boş Bırakılamaz",
        disabled: true,
        span: 4,
      },
      {
        name: "max",
        type: "number",
        title: "Max",
        placeholder: "Max Giriniz...",
        required: true,
        requiredMessage: "Max Değeri Boş Bırakılamaz",
        disabled: true,
        relativeTo: "sertifika",
        span: 4,
      },
      {
        name: "height",
        type: "number",
        title: "Height",
        placeholder: "Height Giriniz...",
        required: true,
        relativeTo: "sertifika",
        requiredMessage: "Height Değeri Boş Bırakılamaz",
        disabled: true,
        span: 4,
      },
      {
        name: "table",
        type: "number",
        title: "Table",
        placeholder: "Table Giriniz...",
        required: true,
        requiredMessage: "Table Değeri Boş Bırakılamaz",
        disabled: true,
        relativeTo: "sertifika",
        span: 4,
        rightIcon: "%",
      },
      {
        name: "totalDepth",
        type: "number",
        title: "Total Depth",
        placeholder: "Total Depth Giriniz...",
        required: true,
        requiredMessage: "Total Depth Değeri Boş Bırakılamaz",
        disabled: true,
        relativeTo: "sertifika",
        span: 4,
        rightIcon: "%",
      },
      {
        name: "girdle",
        type: "number",
        title: "Girdle",
        placeholder: "Girdle Giriniz...",
        required: true,
        relativeTo: "sertifika",
        requiredMessage: "Girdle Değeri Boş Bırakılamaz",
        disabled: true,
        span: 4,
      },
    ],
  },
  {
    colsLenght: "4",
    sectionTitle: "Pırlanta Fiyat Bilgileri",
    groupNumber: 1,
    keyString: "product_cost",
    elements: [
      {
        name: "buy_date",
        type: "datepicker",
        title: "Satin Alma Tarihi",
        placeholder: "Satın Alma Tarihi Giriniz...",
        required: true,
        requiredMessage: "Satın Alma Tarihi Boş Bırakılamaz",
        span: 1,
      },
      {
        name: "rapaportPrice",
        type: "money",
        title: "Rapaport Güncel Fiyatı",
        placeholder: "Rapaport Güncel Fiyatı...",
        required: true,
        requiredMessage: "Rapaport Fiyatı Boş Bırakılamaz",
        rightIcon: "$",
        span: 1,
        disabledRelative: "Sertifikasız",
        relativeTo: "menstrual_status",
        visibleRelative: "Sertifikalı",
      },
      {
        name: "iskonto",
        type: "money",
        title: "İskonto",
        placeholder: "İskonto...",
        required: true,
        requiredMessage: "İskonto Boş Bırakılamaz",
        span: 1,
        rightIcon: "%",
        relativeTo: "menstrual_status",
        visibleRelative: "Sertifikalı",
        disabledRelative: "Sertifikasız",
      },
      {
        name: "pricePerCarat",
        type: "money",
        title: "Price Per Carat",
        placeholder: "Price Per Carat...",
        required: false,
        requiredMessage: "İskonto Boş Bırakılamaz",
        disabled: true,
        rightIcon: "$",

        span: 1,
      },
      {
        name: "total_cost",
        type: "money",
        title: "Toplam Fiyat",
        placeholder: "Toplam Fiyat...",
        required: false,
        requiredMessage: "Toplam Fiyat Bırakılamaz",
        rightIcon: "$",
        colStart: "4",
        colEnd: "5",
        relativeTo: "menstrual_status",
        disabledRelative: "Sertifikalı",
        span: 1,
      },
    ],
  },
];

export const AddRenkliTasSections: Array<FormSectionType> = [
  {
    colsLenght: "8",
    sectionTitle: "Renkli Taş Bilgileri",
    groupNumber: 0,
    keyString: "properties",
    extraElementRelativeTo: "menstrual_status",
    extraElementVisibleRelative: "Sertifikalı",
    extraElements: [
      {
        name: "fromsingleormixed",
        type: "customButtonGroup",
        isCodeRelated: true,
        title: "Tip",
        checkBoxList: ["From Single", "From Mixed"],
        required: true,
        requiredMessage: "Karat Değeri Boş Bırakılamaz",
        checkBoxSetValueItem: "fromsingleormixed",
        span: 4,
        value: "From Single",
      },
      {
        name: "frommixedItem",
        type: "select",
        title: "Mixed Grubu",
        isCodeRelated: true,
        required: true,
        requiredMessage: "Kesim Boş Bırakılamaz",
        relativeTo: "fromsingleormixed",
        visibleRelative: "From Mixed",
        isExtra: true,
        span: 4,
      },
    ],
    elements: [
      {
        name: "menstrual_status",
        isCodeRelated: true,
        type: "customButtonGroup",
        checkBoxList: ["Sertifikalı", "Sertifikasız"],
        required: true,
        requiredMessage: "Karat Değeri Boş Bırakılamaz",
        checkBoxSetValueItem: "menstrual_status",
        span: 8,
      },
      {
        name: "renkliTas",
        type: "select",
        isCodeRelated: true,
        title: "Renkli Taş",
        placeholder: "Renkli Taş Seçiniz...",
        required: true,
        requiredMessage: "Renkli Taş Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        span: 2,
        options: RenkliTasListesiData,
      },
      {
        name: "carat",
        type: "number",
        title: "Karat",
        placeholder: "Karat Giriniz...",
        required: true,
        requiredMessage: "Karat Değeri Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        span: 2,
        // simgeturu: "caratType",
      },
      {
        name: "renk",
        type: "select",
        title: "Renk",
        placeholder: "Renk Seçiniz...",
        required: true,
        requiredMessage: "Renk Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        span: 2,
        options: RenkliTasRenkListesi,
      },
      {
        name: "kesim",
        type: "select",
        title: "Kesim",
        placeholder: "Kesim Giriniz...",
        required: true,
        requiredMessage: "Kesim Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        span: 2,
        options: RenkliTasListesiKesimData,
      },
      {
        name: "mensei",
        type: "select",
        title: "Menşei",
        placeholder: "Menşei Seçiniz...",
        required: false,
        requiredMessage: "Menşei Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        span: 2,
        staticOptions: RenkliTasListesiMenseiList,
      },
      {
        name: "treatment",
        type: "select",
        title: "Treatment",
        placeholder: "Treatment Seçiniz...",
        required: false,
        requiredMessage: "Treatment Boş Bırakılamaz",
        relativeTo: "menstrual_status",
        span: 2,
        options: [
          {
            titleVal: "HEATED",
            valueVal: "HEATED",
          },
          {
            titleVal: "NOT HEATED",
            valueVal: "NOT HEATED",
          },
        ],
      },
      {
        name: "pricePerCarat",
        type: "money",
        title: "Price Per Carat",
        placeholder: "Price Per Carat...",
        required: true,
        requiredMessage: "Karat Başına Maliyet Giriniz",
        isCurrency: true,
        rightIcon: "$",
        disabled: true,
        span: 2,
      },
      {
        name: "total_cost",
        type: "money",
        title: "Toplam Fiyat",
        placeholder: "Toplam Fiyat...",
        required: true,
        requiredMessage: "Toplam Fiyat Boş Bırakılamaz",
        disabled: false,
        rightIcon: "$",
        span: 2,
      },
      {
        name: "supplier_id",
        type: "select",
        title: "Tedarikçi",
        placeholder: "Tedarikçi Giriniz...",
        relativeTo: "menstrual_status",
        required: false,
        requiredMessage: "Tedarikçi Değeri Boş Bırakılamaz",
        span: 2,
        customOptions: TedarikciCustomListType,
        isTedarikci: true,
      },
      // {
      //   name: "sertifikaDosyasi",
      //   type: "file",
      //   title: "Sertifika Dosyası",
      //   placeholder: "Sertifika Dosyası Seçiniz...",
      //   required: false,
      //   requiredMessage: "Sertifika Dosyası  Boş Bırakılamaz",
      //   disabled: true,
      //   span: 2,
      //   relativeTo: "menstrual_status",
      //   visibleRelative: "Sertifikalı",
      // },
    ],
  },
  {
    visibleRelativeColumn: "menstrual_status",
    colsLenght: "12",
    visibleRelativeToValue: "Sertifikalı",
    sectionTitle: "Sertifika Bilgileri",
    groupNumber: 1,
    keyString: "product_certificate",
    elements: [
      {
        name: "sertifika",
        type: "select",
        title: "Sertifika",
        placeholder: "Sertifika Seçiniz...",
        required: false,
        span: 3,
        requiredMessage: "Sertifika Değeri Boş Bırakılamaz",
        options: PirlantaSertifikaKodlari,
      },
      {
        name: "sertifikaNo",
        type: "text",
        relativeTo: "sertifika",
        title: "Sertifika No",
        placeholder: "Sertifika No Giriniz...",
        required: true,
        requiredMessage: "Sertifika No Değeri Boş Bırakılamaz",
        disabled: false,
        span: 3,
        isLinkedWithIcon: true,
        rightIcon: <FaGlobe />,
        extraFunction: GenerateSertificateUrl,
      },
      {
        name: "sertifikaTarihi",
        type: "datepicker",
        title: "Sertifika Tarihi",
        placeholder: "Sertifika Tarihi Giriniz...",
        required: true,
        requiredMessage: "Sertifika Tarihi Değeri Boş Bırakılamaz",
        disabled: false,
        relativeTo: "sertifika",
        span: 3,
      },

      {
        name: "sertifikaDosyasi",
        type: "file",
        relativeTo: "sertifika",
        title: "Sertifika Dosyası",
        placeholder: "Sertifika Dosyası Seçiniz...",
        required: false,
        requiredMessage: "Sertifika No Değeri Boş Bırakılamaz",
        disabled: true,
        span: 3,
      },
    ],
  },
];

export const AmbarOptionsData: CustomOptionType[] = [
  { titleVal: "Galataport", valueVal: "Galataport" },
  { titleVal: "Zorlu", valueVal: "Zorlu" },
  { titleVal: "Anlı", valueVal: "Anlı" },
  { titleVal: "OnlyOne", valueVal: "OnlyOne" },
  { titleVal: "Luxia", valueVal: "Luxia" },
  { titleVal: "Merkez", valueVal: "Merkez" },
];
